--liquibase formatted sql

--changeset credit-service:002-create-retry-task
CREATE TABLE retry_task (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         VARCHAR(64)   NOT NULL,
    sequence_key VARCHAR(255)  NOT NULL,
    payload      CLOB          NOT NULL,
    attempt      INT           NOT NULL,
    last_error   VARCHAR(2000),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_retry_task_sequence_key
    ON retry_task (sequence_key);
