--liquibase formatted sql

--changeset credit-service:003-create-credit-tariff
CREATE TABLE credit_tariff (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255) NOT NULL,
    interest_rate           DECIMAL(19, 4) NOT NULL,
    payment_interval_minutes INT NOT NULL
);
