--liquibase formatted sql

--changeset credit-service:004-create-credit
CREATE TABLE credit (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          VARCHAR(255) NOT NULL,
    tariff_id        BIGINT NOT NULL,
    total_amount     DECIMAL(19, 4) NOT NULL,
    remaining_amount DECIMAL(19, 4) NOT NULL,
    status           VARCHAR(32) NOT NULL,
    started_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    next_payment_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_credit_tariff FOREIGN KEY (tariff_id) REFERENCES credit_tariff (id)
);

CREATE INDEX idx_credit_user_id ON credit (user_id);
