--liquibase formatted sql

--changeset credit-service:005-create-credit-payment
CREATE TABLE credit_payment (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credit_id BIGINT NOT NULL,
    paid_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    amount    DECIMAL(19, 4) NOT NULL,
    CONSTRAINT fk_credit_payment_credit FOREIGN KEY (credit_id) REFERENCES credit (id)
);

CREATE INDEX idx_credit_payment_credit_id ON credit_payment (credit_id);
