name: InternetBanking
options:
  bundleIdPrefix: tarchenko
  deploymentTarget:
    iOS: "18.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  xcodeVersion: "1620"
settingGroups:
  shared:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    DEVELOPMENT_TEAM: BUF892U9LY
    GENERATE_INFOPLIST_FILE: YES
targets:
  BankClient:
    type: application
    platform: iOS
    sources: [BankClient]
    scheme:
      shared: true
    settings:
      groups: [shared]
      base:
        PRODUCT_BUNDLE_IDENTIFIER: tarchenko.BankClient
        INFOPLIST_KEY_CFBundleDisplayName: "Банк — Клиент"
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
  BankEmployee:
    type: application
    platform: iOS
    sources: [BankEmployee]
    scheme:
      shared: true
    settings:
      groups: [shared]
      base:
        PRODUCT_BUNDLE_IDENTIFIER: tarchenko.BankEmployee
        INFOPLIST_KEY_CFBundleDisplayName: "Банк — Сотрудник"
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
